version: "3.8"

services:
  profile:
    build:
      context: ./profile
      dockerfile: Dockerfile
    container_name: profile-service
    ports:
      - "33501:33501"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - my-network
    volumes:
      - maven_repo:/root/.m2

  address:
    build:
      context: ./address
      dockerfile: Dockerfile
    container_name: address-service
    ports:
      - "33502:33502"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network
    volumes:
      - maven_repo:/root/.m2

  occupation:
    build:
      context: ./occupation
      dockerfile: Dockerfile
    container_name: occupation-service
    ports:
      - "33503:33503"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network
    volumes:
      - maven_repo:/root/.m2

  rules:
    build:
      context: ./rules
      dockerfile: Dockerfile
    container_name: rules-service
    ports:
      - "33504:33504"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network
    volumes:
      - maven_repo:/root/.m2

  redis-master-1:
    image: redis:7-alpine
    container_name: redis-master-1
    ports:
      - "7000:6379"
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - my-network
    volumes:
      - redis_data_master_1:/data

  redis-replica-1:
    image: redis:7-alpine
    container_name: redis-replica-1
    ports:
      - "7001:6379"
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip $(hostname)
    networks:
      - my-network
    volumes:
      - redis_data_replica_1:/data

  redis-cluster-setup:
    image: redis:7-alpine
    container_name: redis-cluster-setup
    depends_on:
      - redis-master-1
      - redis-replica-1
    command: redis-cli --cluster create redis-master-1:6379 redis-replica-1:6379 --cluster-replicas 1 --cluster-yes
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  maven_repo:
  redis_data_master_1:
  redis_data_replica_1:
