server:
  port: 12400

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: workflow
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
app:
  redis:
    host: 127.0.0.1
    port: 6379

